data:
  FUNCTIONS_WORKER_RUNTIME: bm9kZQ==
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXNhZXVzcWF2cHJvZmlsZTtBY2NvdW50S2V5PWZMaWRVcEtZY09LVGg1NURXUFdTRjhsSmJBWC9IUkZSckJoUHQxMXRyQVBkZ0E1eXFtM2Vza2s1SitPME0wd3dNZEpqMzdEQ0p1VHJNa3VqZjZwT3JnPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
apiVersion: v1
kind: Secret
metadata:
  name: hello-keda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-keda
  labels:
    app: hello-keda
spec:
  selector:
    matchLabels:
      app: hello-keda
  template:
    metadata:
      labels:
        app: hello-keda
    spec:
      containers:
      - name: hello-keda
        image: rohitshavili/hello-keda:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: QueueTrigger
        envFrom:
        - secretRef:
            name: hello-keda
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-queue-auth
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: hello-keda
  labels: {}
spec:
  scaleTargetRef:
    name: hello-keda
  pollingInterval: 2
  minReplicaCount: 0
  maxReplicaCount: 30
  triggers:
  - type: azure-queue
    metadata:
      direction: in
      queueName: keda-account
      connectionFromEnv: AzureWebJobsStorage
    authenticationRef:
        name: azure-queue-auth
---

