apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voteapp-demo
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/app-root: "/"
spec:
  rules:
  - host: vote.letsdevops.ml
    http:
      paths:
      - path: /v1
        pathType: Exact
        backend:
          service:
            name: voting-service
            port:
              number: 80

  - host: result.letsdevops.ml
    http:
      paths:
      - path: /v2
        pathType: Exact
        backend:
          service:
            name: result-service
            port:
              number: 80